vespa-engine/cord-19

- src/App/shared/components/NavMenu.js
we can link to more Vespa stuff from the readme files, I think - we can iterate on this
> link to repo-local resources

- src/App/shared/components/NavMenu.js
> only one link in header. link to cloud.vespa.ai from logo

- ABOUT.md
- CONTRIBUTING.md
- README.md
- cord-19-queries.md
- experiment-yourself.md
> cleanup, rename

- src/App/Search/ResultCard.js
- src/App/Search/index.js
- src/App/index.js
- src/App/shared/Fetcher.js
- src/App/shared/components/Footer.js
- src/App/shared/components/NavMenu.js
Some improvements from today, this is on `gh-pages` with 96126abdf500a63bf7ed0b1616dc726b96d88660
> Improve result cards & add footer

- cord-19-queries.md
> Add query and api doc

- src/App/Main.js
Source for changes in 426c69f55c7f5b45d346297888de9b5bf50ed6f6
> Add sample queries to frontpage

- experiment-yourself.md
@freva or @jobergum please merge - lets continue this Monday
> unfinished guide

- src/App/shared/components/NavMenu.js
> link to root

- public/index.html
> Add Google Analytics tracking

- cord-19-queries.md
> Add more examples

- cord-19-queries.md
> example last name query

- README.md
- src/App/shared/components/Footer.js
> Update with new dataset published 2020-03-27

- cord-19-queries.md
> Add link to Kaggle Notebook

- CONTRIBUTING.md
@kkraune : Please review.
FYI: @freva.
> Include info on running frontend locally

- package.json
- src/App/Article/index.js
- src/App/Search/ResultCard.js
- src/App/index.js
- yarn.lock
make simplistic article work... let's make the improvements on another PR.
> simplistic article view

- src/App/Article/index.js
Note that currently the first hit is the same as the asked for, we need make a change to drop it either in the frontend or in backend.
> change query for related articles

- src/App/Search/ResultCard.js
I would like to get rid of the entire body, but I can't figure our how when this is styled by hacking the css settings instead of the way that is described in the documentation at https://react-bootstrap.github.io/components/cards/#border-color
> Less border

- src/App/shared/components/Footer.js
- src/App/shared/components/NavMenu.js
@bratseth Please review.
FYI: @freva
> Move Vespa logo to footer and add name in header

- .github/workflows/deploy-ui.yaml
- src/App/shared/components/Footer.js
Testing PR builds for frontend. Wait with merging until we see that it works on the PR.
> Add PR build job without deploy

- src/App/Article/index.js
- src/App/Search/Sidebar.js
@freva please review and merge :)
> Handle no citationns, and merge with scite-found citations

- .github/workflows/deploy-ui.yaml
> Checkout from git on deploy

- .github/workflows/deploy-ui.yaml
Trying again to fix broken YAML syntax and make deploy work.
> Try fixing YAML syntax

- cord-19-queries.md
> Add note on ranking and related api

- src/App/Article/index.js
@freva or @ldalves please review but do not merge. There's a problem when changing the pagination display to something with a different number of articles.
> Paginate citing articles

- src/App/Search/ResultCard.js
- src/App/Search/Sidebar.js
- src/App/Search/Utils.js
- src/App/Search/index.js
- src/App/shared/components/SearchForm.js
Need to test when the backend is fixed before merging.
> Search similar

- README.md
> add contact info

- src/App/Search/Sidebar.js
Not perfectly happy with these but at least a bit better. 
Looks to me we should adjust the font colors as well.
> Navbar colors that matches the new header better

- src/App/Search/ResultCard.js
- src/App/Search/Sidebar.js
- src/index.css
This is the black color we have specified in the design guide.
> adjusts tons of blank

- src/App/Article/index.js
@freva or @ldalves please review and merge.
> Link back to search for similar articles from similar articles view

- src/App/Search/index.js
@ldalves please review and merge
> Match clear-all-button-to-search-text-box

- src/App/Main.js
- src/App/shared/components/NavMenu.js
A bit better view when using mobile
> responsive menu

- cord-19-queries.md
And link to the new semantic explanation
> Update with more examples

- README.md
> Updated dataset version

- src/App/Search/SearchOptions.js
- src/App/Search/Utils.js
- src/App/Search/index.js
@freva @jobergum or @bratseth please review.
> Show title of article when searching for related

- README.md
- src/App/shared/components/Footer.js
> New version

- src/App/Main.js
- src/App/shared/components/Footer.js
> Richer query examples - less question type queries 

- src/App/shared/components/Footer.js
> Update to 2020-04-24 version

- src/App/shared/components/Footer.js
> Update to 2020-05-01 version

- README.md
@jobergum / @freva / @oyving please review/merge
> link to key management

- README.md
- src/App/shared/components/Footer.js
> correct date

- src/App/Search/index.js
... not sure why dependency changes like in the last two PRs do not result in something to commit, so deployment job fails in https://github.com/vespa-engine/cord-19/actions - see if this goes through
> dummy commit for deployment

- public/index.html
> Clean up unused JS

- src/App/Search/Utils.js
> Remove attributes

- src/App/Search/ResultCard.js
- src/App/Search/SearchOptions.js
> remove unused vars

- src/App/Article/index.js
- src/App/Search/Utils.js
- src/App/Search/index.js
> use vector similarity

- src/App/Main.js
- src/App/Search/SearchOptions.js
- src/App/Search/Utils.js
> More interesting questions and change default to colbert

- src/App/Search/SearchOptions.js
- src/App/Search/Utils.js
> Add hybrid rank option and make it default

- src/App/Search/SearchOptions.js
- src/App/Search/Utils.js
> Add cross-encoder ranking option

- yarn.lock
Reverts vespa-engine/cord-19#162
> Revert "Update dependency fomantic-ui-css to v2.9.2"

- package.json
- yarn.lock
Reverts vespa-engine/cord-19#171
> Revert "Update dependency prettier to v3"

- package.json
- yarn.lock
Reverts vespa-engine/cord-19#195
> Revert "Update dependency lint-staged to v15"

- package.json
- yarn.lock
Reverts vespa-engine/cord-19#215
> Revert "Update dependency husky to v9"

- .github/workflows/deploy-ui.yaml
- index.html
> Add shutdown page and simplify build to deploy only index.html
